plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.arish.eggs'
    compileSdk 33

    defaultConfig {
        applicationId "com.arish.eggs.v14"
        minSdk 24
        targetSdk 33
        
        versionCode project.hasProperty('autoVersionCode') ? project.property('autoVersionCode').toInteger() : 1
        versionName project.hasProperty('autoVersionName') ? project.property('autoVersionName').toString() : "5.2"
        
        resValue "string", "app_name", "Arish Eggs"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
    buildFeatures { compose true }
    composeOptions { kotlinCompilerExtensionVersion '1.4.3' }
}


dependencies {
    implementation 'androidx.core:core-ktx:1.10.0'
    implementation 'androidx.activity:activity-compose:1.7.2'
    implementation platform('androidx.compose:compose-bom:2023.05.01')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.material3:material3'
    implementation "androidx.compose.material:material-icons-extended"
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1'
    implementation "androidx.datastore:datastore-preferences:1.0.0"
    implementation "com.google.code.gson:gson:2.10.1"
}
    
